# Generated by Django 3.1.4 on 2021-01-05 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210105_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_start',
            field=models.TimeField(default=datetime.datetime(2021, 1, 5, 14, 31, 23, 828002)),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_joined',
            field=models.BooleanField(default=None),
        ),
    ]
