# Generated by Django 3.1.4 on 2021-01-05 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210105_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=512)),
                ('player_name', models.CharField(max_length=512)),
                ('player_choice', models.CharField(choices=[('RO', 'ROCK'), ('PA', 'PAPER'), ('SC', 'SCISSORS'), ('SP', 'SPOCK'), ('LI', 'LIZARD')], default=None, max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_1_input',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2_input',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_start',
            field=models.TimeField(default=datetime.datetime(2021, 1, 5, 15, 6, 8, 224629)),
        ),
        migrations.AddField(
            model_name='game',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_game', to='game.players'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_game', to='game.players'),
        ),
    ]
