# Generated by Django 3.1.4 on 2021-01-05 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210105_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_game', to='game.players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_start',
            field=models.TimeField(default=datetime.datetime(2021, 1, 5, 15, 8, 14, 135460)),
        ),
    ]
