# Generated by Django 3.1.5 on 2021-01-05 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210105_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_start',
            field=models.TimeField(default=datetime.datetime(2021, 1, 5, 13, 54, 57, 886377)),
        ),
    ]
